apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-center-api
  namespace: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: call-center-api
  template:
    metadata:
      labels:
        app: call-center-api
    spec:
      containers:
        - name: nodejs-app
          image: 692859934069.dkr.ecr.ap-south-1.amazonaws.com/callcenterapp:93463c3558cc7ef6732667e50a38960a2efea485
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
