apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-center-api
  namespace: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: call-center-api
  template:
    metadata:
      labels:
        app: call-center-api
    spec:
      containers:
        - name: nodejs-app
          image: 692859934069.dkr.ecr.ap-south-1.amazonaws.com/callcenterapp:7272d0f942452d6b7ab316a79596ad6fcb3d8cac
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
